version: '2.3'
services:
  mysql:
    image: mariadb
    # Debug access:
    #ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
  phpbb:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_NAME
      - DBPASSWD
      - PHPBB_INSTALLED
      - AUTO_DB_MIGRATE
    volumes:
      - ./ssl:/etc/apache2/ssl
  backup:
    image: blueimp/phpbb-s3-backup
    environment:
      - DBPASSWD
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes_from:
      - phpbb
