services:
  mysql:
    image: mariadb
    # Debug access:
    #ports:
    #  - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
  phpbb:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/apache2/ssl
    env_file: .env
  #backup:
  #  image: blueimp/phpbb-s3-backup
  #  volumes_from:
  #    - phpbb
