services:
  mysql:
    image: mariadb
    # Debug access:
    #ports:
    #  - "3306:3306"
  phpbb:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/apache2/ssl
  backup:
    image: blueimp/phpbb-s3-backup
    volumes_from:
      - phpbb
